### ISSUE TITLE
关于blur_map的计算过程问题

### ISSUE THREAD

**Issue by SWALLOWhajnal** [huicongzhang/BSSTNet#4]
计算模糊映射时，模糊映射的首个时间步 ：blur_map_first是由flow_backwards第一步单独平方和得到的，为什么不是flow_backwards第一步和flow_forwards第一步的平方后和来得到呢？有什么寓意吗

**Comment by huicongzhang** [comment]
因为，flow_backwards[0]表示的是第0号帧到第1号帧的光流，而flow_forwards[0]是第1号帧到第0号帧的光流。而blur_map_first表示的是第0号帧的运动因此只采用flow_backwards[0]
